# Generated by Django 2.2.13 on 2021-02-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_1', models.CharField(max_length=255, null=True)),
                ('category_2', models.CharField(max_length=255, null=True)),
                ('category_3', models.CharField(max_length=255, null=True)),
                ('category_4', models.CharField(max_length=255, null=True)),
                ('category_5', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
