# Generated by Django 2.2.13 on 2021-02-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='category_2',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='category_3',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='category_4',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='category_5',
        ),
        migrations.AlterField(
            model_name='temp',
            name='category_1',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
