# Generated by Django 2.2.13 on 2021-02-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210211_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='category_1',
            new_name='categories',
        ),
    ]
