# Generated by Django 2.2.13 on 2021-02-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_picture',
        ),
    ]
